package com.example.demo.repository;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * 토큰 관리 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class JwtDTO {

	/** 엑세스 토큰. */
	private String accesstoken;

	/** 리프레시 토큰. */
	private String refreshtoken;



}
